worker_process auto;

events {
    worker_connections 1024;
    use epoll;
    multi_accept on;
}

http {
    access_log off;
    error_log /dev/null;

    upstream api {
        least_conn;
        server api1:3000;
        server api2:3000;
        keepalive 100;
    }

    server {
        listen 9999;

        location / {
            proxy_pass http://api;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
        }
    }
}
